/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.joelson.mattias.deeptown;

public class DeeptownCalculator {

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new DeeptownCalculator().getGreeting());
    }
}
