/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.joelson.mattias.deeptown;

import org.junit.Test;
import static org.junit.Assert.*;

public class DeepTownCalculatorTest {
    @Test public void appHasAGreeting() {
        DeepTownCalculator classUnderTest = new DeepTownCalculator();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
